### ISSUE TITLE
System.InvalidOperationException: 'Sequence contains no matching element'

### ISSUE THREAD

**Issue by ozitraveller** [JuergenGutsch/graphql-aspnetcore#3]
{
  book(isbn: "822-5-315140-65-3"){
    isbn,
    name
  }
}

System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Sequence contains no matching element
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at GraphQlDemo.Data.BookRepository.BookByIsbn(String isbn) in D:\Test2\graphql-aspnetcore\GraphQlDemo\data\PersonRepository.cs:line 65
   at GraphQlDemo.Query.GraphQlTypes.BooksQuery.<>c__DisplayClass0_0.<.ctor>b__0(ResolveFieldContext`1 context) in D:\Test2\graphql-aspnetcore\GraphQlDemo.Query\GraphQlTypes\BookQuery.cs:line 16
   at GraphQL.Resolvers.FuncFieldResolver`2.GraphQL.Resolvers.IFieldResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Instrumentation.MiddlewareResolver.<Resolve>d__2.MoveNext()

**Comment by JuergenGutsch** [comment]
Hi @ozitraveller, 
This is not an iyyue of the library, but a small one with the demo application.
The database used in the demo is created in memory on the application start. That means the ID's will change on every start. Before querying a specific book with an specific ID, you need to be sure the ID exists in the database. Just query the entire list first and than pick an ID to query for :)
Cheers

**Comment by ozitraveller** [comment]
Awesome thanks! :)

**Comment by ozitraveller** [comment]
How to I phrase a query to return all the books

{
  book
}

**Comment by JuergenGutsch** [comment]
```
{
  books{
    isbn,
    name,
    author{
      id,
      name,
      birthdate
    }
  }
}
```
or 
```
{
  books(limit: 20) {
    isbn,
    name,
    author{
      id,
      name,
      birthdate
    }
  }
}
```

**Comment by ozitraveller** [comment]
Thanks you! :)
